FROM golang:1.23-alpine AS build

WORKDIR /src
COPY go.mod ./
COPY server/ ./server/
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /droidtv-remote ./server

FROM scratch
WORKDIR /app
COPY --from=build /droidtv-remote /app/droidtv-remote
COPY VERSION /app/VERSION
COPY client/ /app/client/

ARG SERVER_PORT=7503
ENV SERVER_PORT=${SERVER_PORT}
EXPOSE ${SERVER_PORT}
VOLUME ["/app/data"]
ENTRYPOINT ["/app/droidtv-remote"]
